# Generated by Django 3.0.4 on 2021-04-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propreties',
            name='principale_image',
            field=models.ImageField(default='images.png', upload_to=''),
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=160)),
                ('location', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('wtsp', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=30)),
                ('propreties', models.ManyToManyField(to='core.Propreties')),
            ],
        ),
    ]
