# Generated by Django 3.0.4 on 2021-04-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210423_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='propreties',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
