# Generated by Django 3.0.4 on 2021-04-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210423_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='propreties',
            name='description',
            field=models.TextField(),
        ),
    ]
