# Generated by Django 3.0.4 on 2021-04-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210423_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='propreties',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
