# Generated by Django 3.0.4 on 2021-04-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_propreties_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propreties',
            name='status',
            field=models.CharField(choices=[('sell', 'sell'), ('rent', 'rent')], max_length=30),
        ),
    ]
