# Generated by Django 3.0.4 on 2021-04-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210424_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propreties',
            name='chambres',
        ),
        migrations.AddField(
            model_name='propreties',
            name='bath_rooms',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='propreties',
            name='beds_rooms',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='propreties',
            name='extra_feature',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='propreties',
            name='kitchen',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='propreties',
            name='living_rooms',
            field=models.CharField(default='', max_length=30),
        ),
    ]
