# Generated by Django 3.0.4 on 2021-04-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210424_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propreties',
            name='description',
        ),
        migrations.AddField(
            model_name='propreties',
            name='full_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='propreties',
            name='mini_des',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='propreties',
            name='extra_feature',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
