# Generated by Django 3.0.4 on 2021-04-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210424_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='propreties',
            name='list_images',
            field=models.ManyToManyField(blank=True, to='core.ListImages'),
        ),
    ]
