# Generated by Django 3.0.4 on 2021-04-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210424_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='propreties',
            name='prop_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
