# Generated by Django 3.0.4 on 2021-04-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_propreties_prop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='image',
            field=models.ImageField(default='images.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='owners',
            name='printest',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='owners',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='owners',
            name='twitter',
            field=models.URLField(default=''),
        ),
    ]
