# Generated by Django 3.0.4 on 2021-04-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210424_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='office',
            field=models.CharField(default='', max_length=30),
        ),
    ]
