# Generated by Django 3.0.4 on 2021-04-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210424_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to=''),
        ),
    ]
