# Generated by Django 3.0.4 on 2021-04-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propreties',
            name='comment',
        ),
        migrations.AddField(
            model_name='propreties',
            name='comment',
            field=models.ManyToManyField(to='core.Comment'),
        ),
    ]
