# Generated by Django 3.0.4 on 2021-04-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='blog_bg.jpg', upload_to=''),
        ),
    ]
