# Generated by Django 3.0.4 on 2021-04-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210425_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('propretie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Propreties')),
            ],
        ),
        migrations.AddField(
            model_name='owners',
            name='message',
            field=models.ManyToManyField(to='core.Message'),
        ),
    ]
