# Generated by Django 3.0.4 on 2021-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210426_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='comment',
            new_name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
